AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ve-project-sam

  Sample SAM Template for ve-project-sam

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs24.x
    Architectures:
      - x86_64

    LoggingConfig:
      LogFormat: JSON
Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "ve-project-${AWS::AccountId}-${AWS::Region}-data"

  VideosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VIDEO_DETAILS
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: video_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: video_id
          KeyType: RANGE

  CreateVideoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create-video/
      Handler: app.lambdaHandler
      Environment:
        Variables:
          TABLE_NAME: !Ref VideosTable
          DATA_BUCKET: !Ref DataBucket
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VideosTable
        - S3WritePolicy:
            BucketName: !Ref DataBucket
      Events:
        CreateVideo:
          Type: Api
          Properties:
            Path: /videos
            Method: post

  GetVideoByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-video-by-id/
      Handler: app.lambdaHandler
      Environment:
        Variables:
          TABLE_NAME: !Ref VideosTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref VideosTable
      Events:
        GetVideo:
          Type: Api
          Properties:
            Path: /videos/{videoId}
            Method: get

  GetAllVideosFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-all-videos/
      Handler: app.lambdaHandler
      Environment:
        Variables:
          TABLE_NAME: !Ref VideosTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref VideosTable
      Events:
        GetAllVideos:
          Type: Api
          Properties:
            Path: /videos
            Method: get

  TranscriptionQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-transcription-queue"

  ProcessUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: process-video-upload/
      Handler: app.lambdaHandler
      Environment:
        Variables:
          TABLE_NAME: !Ref VideosTable
          TRANSCRIPTION_QUEUE_URL: !Ref TranscriptionQueue
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VideosTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt TranscriptionQueue.QueueName
      Events:
        S3Upload:
          Type: S3
          Properties:
            Bucket: !Ref DataBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: videos/

  ProcessTranscriptionCompletedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: process-transcription-completed/
      Handler: app.lambdaHandler

      Environment:
        Variables:
          TABLE_NAME: !Ref VideosTable

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VideosTable

      Events:
        TranscriptionCreated:
          Type: S3
          Properties:
            Bucket: !Ref DataBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: transcriptions/

  CreateTranscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create-transcription/
      Handler: app.lambdaHandler
      Environment:
        Variables:
          TABLE_NAME: !Ref VideosTable
          DATA_BUCKET: !Ref DataBucket
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VideosTable
        - S3ReadPolicy:
            BucketName: !Ref DataBucket
        - S3WritePolicy:
            BucketName: !Ref DataBucket
        - Statement:
            Effect: Allow
            Action:
              - transcribe:StartTranscriptionJob
              - transcribe:GetTranscriptionJob
            Resource: "*"
      Events:
        TranscriptionQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt TranscriptionQueue.Arn
            BatchSize: 1

Outputs:
  APIGatewayEndpoint:
    Description: API GTW base URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
